home/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', views.home, name='home'),
    path('detail/<int:id>', views.detail, name="detail"),
    path('esthaniye/', views.esthaniye, name='esthaniye'),
    path('rajnitic/', views.rajnitic, name='rajnitic'),
    path('samsamyak/', views.samsamyak, name='samsamyak'),
    path('khelkud/', views.khelkud, name='khelkud'),
    path('antarastriye/', views.antarastriye, name='antarastriye'),
    path('suchana/', views.suchana, name='suchana'),
    path('sowasthya/', views.sowasthya, name='sowasthya'),
    path('bichar/', views.bichar, name='bichar'),
    path('rochak/', views.rochak, name='rochak'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rnkhabar/urls.py
from django.contrib import admin
from django.urls import path, include
admin.site.site_header = "RNKHABAR Admin"
admin.site.site_title = "RNKHABAR Admin Portal"
admin.site.index_title = "Welcome to RNKHABAR News Portal"

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('ckeditor', include('ckeditor_uploader.urls')),
]

home/models.py
from django.db import models
from django.utils.html import format_html
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=200)
    category_image = models.ImageField(upload_to='image')

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title


class News(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=300)
    type = models.CharField(max_length=150)
    author = models.CharField(max_length=150)
    image = models.ImageField(upload_to='image')
    detail = RichTextUploadingField()
    add_time = models.DateTimeField(auto_now_add=True)
    views = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = 'News'

    def image_post(self):
        return format_html('<img src="/mymedia/{}" alt="img" style="width:40px;height:40px;"  />'.format(self.image))

    def __str__(self):
        return self.title

home/views.py
from random import randrange
from django.shortcuts import render
from .models import News, Category
from django.core.paginator import Paginator
# Create your views here.


def home(request):
    headline = News.objects.order_by('-add_time')
    first_news = News.objects.order_by('-add_time').first
    three_news = News.objects.order_by('-add_time')[1:2]
    three_categories = Category.objects.all()[0:9]
    return render(request, 'home/index.html', {
        'headline': headline,
        'first_news': first_news,
        'three_news': three_news,
        'three_categories': three_categories,

    })

# Deatil Page


def detail(request, id):
    headline = News.objects.order_by('-add_time')
    news = News.objects.get(pk=id)
    news.views = news.views + 1
    news.save()
    category = Category.objects.get(id=news.category.id)
    rel_news = News.objects.filter(category=category).exclude(id=id).order_by('-add_time')[:4]
    return render(request, 'home/detail.html', {
        'headline': headline,
        'news': news,
        'related_news': rel_news

    })
# esthaniye


def esthaniye(request):
    
    # Esthaniyes = Category.objects.all()[0:1] # comment this line
    Esthaniyes = Category.objects.filter(title="स्थानीय")  # use this
    # print("Result : ", Esthaniyes)
    c_1 = News.objects.filter(category__title="स्थानीय").order_by('-add_time')
    # pagination
    pagination = Paginator(c_1, 20)
    page_number = request.GET.get('page')
    newsdata_final = pagination.get_page(page_number)
    # print(c_1)

    context = {
        'Esthaniyes': Esthaniyes,
        # 'c_1': c_1,
        'c_1': newsdata_final,

    }
    return render(request, 'home/esthaniye.html', context)


# def edetail(request, id):
#     ndetail = News.objects.get(id=id)
#     context = {
#         'ndetail': ndetail
#     }
#     return render(request, 'home/detail.html', context)
# rajnitic


def rajnitic(request):
    Rajnitic = Category.objects.filter(title="राजनीति")
    R_news = News.objects.filter(
        category__title="राजनीति").order_by('-add_time')
    pagination = Paginator(R_news, 20)
    page_number = request.GET.get('page')
    newsdata_final = pagination.get_page(page_number)

    context = {
        'Rajnitic': Rajnitic,
        'R_news': newsdata_final,

    }
    return render(request, 'home/rajnitic.html', context)


# samsamyak


def samsamyak(request):
    Samsamyak = Category.objects.filter(title="समसम्यक")
    sm_news = News.objects.filter(
        category__title="समसम्यक").order_by('-add_time')
    pagination = Paginator(sm_news, 20)
    page_number = request.GET.get('page')
    newsdata_final = pagination.get_page(page_number)
    context = {
        'Samsamyak': Samsamyak,
        'sm_news': newsdata_final
    }
    return render(request, 'home/samsamyak.html', context)


# khelkud


def khelkud(request):
    Khelkud = Category.objects.filter(title="खेलकुद")
    K_news = News.objects.filter(
        category__title="खेलकुद").order_by('-add_time')
    pagination = Paginator(K_news, 20)
    page_number = request.GET.get('page')
    newsdata_final = pagination.get_page(page_number)
    context = {
        'Khelkud': Khelkud,
        'K_news': newsdata_final
    }
    return render(request, 'home/khelkud.html', context)


# antarastriye


def antarastriye(request):
    Antarastriye = Category.objects.filter(title="अन्तरास्ट्रिय")
    A_news = News.objects.filter(
        category__title="अन्तरास्ट्रिय").order_by('-add_time')
    pagination = Paginator(A_news, 20)
    page_number = request.GET.get('page')
    newsdata_final = pagination.get_page(page_number)
    context = {
        'Antarastriye': Antarastriye,
        'A_news': newsdata_final
    }
    return render(request, 'home/antarastriye.html', context)


# suchana parbidhi


def suchana(request):
    Suchana = Category.objects.filter(title="सूचना प्रबिधि")
    su_news = News.objects.filter(
        category__title="सूचना प्रबिधि").order_by('-add_time')
    pagination = Paginator(su_news, 20)
    page_number = request.GET.get('page')
    newsdata_final = pagination.get_page(page_number)
    context = {
        'Suchana': Suchana,
        'su_news': newsdata_final
    }
    return render(request, 'home/suchana.html', context)
# sowathya


def sowasthya(request):
    Sowasthya = Category.objects.filter(title="स्वास्थ्य")
    so_news = News.objects.filter(
        category__title="स्वास्थ्य").order_by('-add_time')
    pagination = Paginator(so_news, 20)
    page_number = request.GET.get('page')
    newsdata_final = pagination.get_page(page_number)
    context = {
        'Sowasthya': Sowasthya,
        'so_news': newsdata_final
    }
    return render(request, 'home/sowasthya.html', context)
# bichar


def bichar(request):
    Bichar = Category.objects.filter(title="विचार")
    bi_news = News.objects.filter(
        category__title="विचार").order_by('-add_time')
    pagination = Paginator(bi_news, 20)
    page_number = request.GET.get('page')
    newsdata_final = pagination.get_page(page_number)
    context = {
        'Bichar': Bichar,
        'bi_news': newsdata_final
    }
    return render(request, 'home/bichar.html', context)
# rochak


def rochak(request):
    Rochak = Category.objects.filter(title="रोचक")
    ro_news = News.objects.filter(
        category__title="रोचक").order_by('-add_time')
    pagination = Paginator(ro_news, 20)
    page_number = request.GET.get('page')
    newsdata_final = pagination.get_page(page_number)
    context = {
        'Rochak': Rochak,
        'ro_news': newsdata_final
    }
    return render(request, 'home/rochak.html', context)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="welcome to rn khabar">
<meta name="keywords" content="rnkhabar, news, nepali news, nepal">
<meta name="author" content="rn sah">
 
  <!-- CSS -->
  {% load static %}
  <link rel="icon" href="{% static 'images/fevi.png' %}" type="image/jpg" sizes="16x16">
  <link rel="stylesheet" type="text/css" href="{% static 'css/internal.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/owl.theme.default.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/animate.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'sass/main.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'sass/responsive.css' %}">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
    integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  <link
    href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
    rel="stylesheet">
  <!-- js -->
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v13.0" nonce="y7MveuHF"></script>
  <title> rnkhabar | nepali news | welcome to rnkhabar </title>
</head>

<body>
    {% include 'home/header.html' %}
 {% block body %}
 
 {% endblock %}
 {% include 'home/footer.html' %}
 
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/internal.min.js' %}"></script>

</body>

</html>

templates/home/antarastriye.html
{% extends 'base.html' %}
{% block body %}
			<main class="container mt-3 mb-5" id="news-wrapper">
			<div class="row">
			{% for i in Antarastriye %}
			
			<h3 class="border-bottom pb-1 my-4">{{i.title}}</h3>
			{% endfor %}
			<!-- Category Box -->

			{% for Category in A_news %}
             <div class="col-md-3 mb-4">
          <div class="card">
            <a href="/detail/{{Category.id}}">
              <img src="{{Category.image.url}}" class="card-img-top" alt="img">
              <div class="card-body">
                <h5 class="card-title">{{Category.title | truncatechars:100 }}</h5>
                <p class="card-text">{{Category.detail | truncatechars:100 | safe }}
                </p>
                <span>By : {{Category.author}}</span> <span>/</span>
                <span>{{Category.type}}</span> <span>/</span>
                <span>{{Category.add_time | date:"d M Y"}}</span>
              </div>
            </a>
          </div>
        </div>


			{% endfor%}
			<nav aria-label="Page navigation example">
  <ul class="pagination">
	  {% if A_news.has_previous %}
    <li class="page-item"><a class="page-link" href="/antarastriye/?page=1">First</a></li>
    <li class="page-item"><a class="page-link" href="/antarastriye/?page={{A_news.previous_page_number}}">Previous</a></li>
	{% endif %}
    
	  {% if A_news.has_next %}
    <li class="page-item"><a class="page-link" href="/antarastriye/?page={{A_news.next_page_number}}">Next</a></li>
  {% endif %}
</ul>
</nav>
			</div>
			</main>
			
{% endblock%}

templates/home/bichar.html
{% extends 'base.html' %}
{% block body %}
			<main class="container mt-3 mb-5" id="news-wrapper">
			<div class="row">
			{% for i in Bichar %}
			
			<h3 class="border-bottom pb-1 my-4">{{i.title}}</h3>
			{% endfor %}
			<!-- Category Box -->

			{% for Category in bi_news %}
             <div class="col-md-3 mb-4">
          <div class="card">
            <a href="/detail/{{Category.id}}">
              <img src="{{Category.image.url}}" class="card-img-top" alt="img">
              <div class="card-body">
                <h5 class="card-title">{{Category.title | truncatechars:100 }}</h5>
                <p class="card-text">{{Category.detail | truncatechars:100 | safe }}
                </p>
                <span>By : {{Category.author}}</span> <span>/</span>
                <span>{{Category.type}}</span> <span>/</span>
                <span>{{Category.add_time | date:"d M Y"}}</span>
              </div>
            </a>
          </div>
        </div>


			{% endfor%}
			<nav aria-label="Page navigation example">
  <ul class="pagination">
	  {% if bi_news.has_previous %}
    <li class="page-item"><a class="page-link" href="/bichar/?page=1">First</a></li>
    <li class="page-item"><a class="page-link" href="/bichar/?page={{bi_news.previous_page_number}}">Previous</a></li>
	{% endif %}
    
	  {% if bi_news.has_next %}
    <li class="page-item"><a class="page-link" href="/bichar/?page={{bi_news.next_page_number}}">Next</a></li>
  {% endif %}
</ul>
</nav>
			</div>
			</main>
			
{% endblock%}

templates/home/detail.html
{% extends 'base.html' %}
{% block body %}
 <section id="detail-news-views">
<main class="container mt-3 mb-5">
	<!-- featured news -->
	<div class="row my-3">
		<!-- Left -->
		<div class="col-md-8">
			<div class="card mb-3">
			  <div class="card-body"> 
				  <div class="views-detail-news">
				   <span>By : {{news.author}}</span> <span>/</span>
                <span>{{news.type}}</span> <span>/</span>
                <span>{{news.add_time | date:"d M Y"}}</span>
				 <span class="name"> {{news.views}}Views</span>
			  </div>
			    <h3 class="card-title" style="text-align:center;"><b>{{news.title}}</b></h3>
				 <img src="{{news.image.url}}" class="card-img-top" alt="{{news.title}}">
				   <hr/>
			    <p class="card-text">{{news.detail | safe}}</p>
				 <div class="fb-share-button" data-href="http://127.0.0.1:8000/detail/{{news.id}}" data-layout="button_count" data-size="large"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2F127.0.0.1%3A8000%2Fdetail%2F38&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Share</a></div>
			  </div>
			  {% comment %} <div class="card-footer">
			  	In <a href="/category/{{news.category.id}}">{{news.category.title}}</a>
			  </div> {% endcomment %}
			 
			  <div class="fb-comments" data-href="http://127.0.0.1:8000/detail/{{news.id}}" data-width="" data-numposts="5"></div>
			</div>

			
		</div>
		<!-- Related News -->
		<div class="col-md-4">
			<h3 class="mb-3 border-bottom pb-1">Related news</h3>
			<!-- Category Box -->
            {% for news in related_news %}
			<div class="card mb-4 relates-news-cover">
            <a href="/detail/{{news.id}}">
              <img src="{{news.image.url}}" class="card-img-top" alt="img">
              <div class="card-body">
                <h5 class="card-title">{{news.title | truncatechars:100 }}</h5>
                <p class="card-text">{{news.detail | truncatechars:100 | safe }}
                </p>
                <span style="color:#666;">By : {{news.author}}</span> <span>/</span>
                <span style="color:#666;">{{news.type}}</span> <span>/</span>
                <span style="color:#666;">{{news.add_time | date:"d M Y"}}</span> <span>/</span>
				<span style="color:#666;">{{news.views}} views</span>
              </div>
            </a>
          </div>
		{% endfor %}
		</div>
	</div>
</main>
</section>
{% endblock %}

templates/home/esthaniye.html
{% extends 'base.html' %}
{% block body %}
			<main class="container mt-3 mb-5" id="news-wrapper">
			<div class="row">
			{% for i in Esthaniyes %}
			
			<h3 class="border-bottom pb-1 my-4">{{i.title}}</h3>
			{% endfor %}
			<!-- Category Box -->

			{% for Category in c_1 %}
             <div class="col-md-3 mb-4">
          <div class="card">
            <a href="/detail/{{Category.id}}">
              <img src="{{Category.image.url}}" class="card-img-top" alt="img">
              <div class="card-body">
                <h5 class="card-title">{{Category.title | truncatechars:100 }}</h5>
                <p class="card-text">{{Category.detail | truncatechars:100 | safe }}
                </p>
                <span>By : {{Category.author}}</span> <span>/</span>
                <span>{{Category.type}}</span> <span>/</span>
                <span>{{Category.add_time | date:"d M Y"}}</span>
              </div>
            </a>
          </div>
        </div>


			{% endfor%}
			<nav aria-label="Page navigation example">
  <ul class="pagination">
	  {% if c_1.has_previous %}
    <li class="page-item"><a class="page-link" href="/esthaniye/?page=1">First</a></li>
    <li class="page-item"><a class="page-link" href="/esthaniye/?page={{c_1.previous_page_number}}">Previous</a></li>
	{% endif %}
    
	  {% if c_1.has_next %}
    <li class="page-item"><a class="page-link" href="/esthaniye/?page={{c_1.next_page_number}}">Next</a></li>
  {% endif %}
</ul>
</nav>
			</div>
			</main>
			
{% endblock%}

templates/home/footer.html
 <!-- footer -->
 {% load static %}
  <div id="footer-wrapper">
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <div class="footer-cover">
            <img src="{% static 'images/logo.png' %}" class="img-fluid" alt="logo">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae dolore aliquam labore excepturi dicta
              facilis
              ab accusantium, illum similique iure commodi molestias illo perspiciatis aspernatur architecto
              consequuntur
              exercitationem obcaecati ad.</p>
          </div>
        </div>
        <div class="col-md-6">
          <div class="footer-cover">
            <h3>Popular Categories</h3>
            <hr class="footer-hr">
            <div class="row">
              <div class="col-5">
               <a href="{% url 'esthaniye' %}"> <li><i class="fas fa-angle-right"></i> स्थानीय</li></a>
               <a href="{% url 'rajnitic' %}"> <li><i class="fas fa-angle-right"></i> राजनीति </li></a>
               <a href="{% url 'samsamyak' %}"> <li><i class="fas fa-angle-right"></i> समसम्यक</li></a>
               <a href="{% url 'khelkud' %}"> <li><i class="fas fa-angle-right"></i> खेलकुद</li></a>
              </div>
               <div class="col-7">
               <a href="{% url 'antarastriye' %}"> <li><i class="fas fa-angle-right"></i> अन्तरास्ट्रिय</li></a>
                <a href="{% url 'suchana' %}"><li><i class="fas fa-angle-right"></i> सूचना प्रबिधि</li></a>
                <a href="{% url 'sowasthya' %}"><li><i class="fas fa-angle-right"></i> स्वास्थ्य</li></a>
               <a href="{% url 'bichar' %}"> <li><i class="fas fa-angle-right"></i> विचार</li></a>
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-3">
          <div class="footer-cover">
            <h3>CONTACT US</h3>
            <hr class="footer-hr">
            <p><i class="fas fa-phone"></i> 0000 00 00 00, 009000900</p>
            <p><i class="far fa-envelope"></i> meashok850@gmail.com</p>
            <p><i class="fas fa-map-marker-alt"></i> Kathmandu, Nepal</p>
          </div>
        </div>
      </div>
      <div class="power-by">
        <span>Copyright © 2022. Developed & Powered by Ashok shah</span>
      </div>
    </div>
  </div>

 

templates/home/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
  <section id="slider-wrapper">
    <div class="container">
      <div class="row">
        <div class="col-md-8 mb-4">
          <div class="news owl-carousel owl-theme">
            <div class="item">
              <div class="card bg-dark text-white">
                <img src="{{first_news.image.url}}" class="card-img" alt="img">
                <div class="card-img-overlay">
                  <h5 class="card-title"><span class="news-type">{{first_news.type}}</span></h5>
                  <a href="/detail/{{first_news.id}}">
                    <p class="card-text">{{first_news.title | truncatechars:200}}</p>
                  </a>
                  <p class="card-text-date">
                    <span class="date"><i class="fa fa-calendar" aria-hidden="true"></i>{{first_news.add_time | date:"d M Y"}}</span> /
                    <span class="name"><i class="fa fa-user" aria-hidden="true"></i> {{first_news.author}}</span> /
                    <span class="name"><i class="fa fa-eye" aria-hidden="true"></i> {{first_news.views}} views</span>
                  </p>
                </div>
              </div>
            </div>
           
          </div>
        </div>
        <div class="col-md-4">
          {% for news in three_news %}
          <div class="card bg-dark text-white">
            <img src="{{news.image.url}}" class="card-img" alt="img">
            <div class="card-img-overlay">
              <h5 class="card-title"><span class="news-type">{{news.type}}</span></h5>
              <a href="/detail/{{news.id}}">
                <p class="card-text">{{news.title | truncatechars:100 }}</p>
              </a>
              <p class="card-text-date">
                <span class="date"><i class="fa fa-calendar" aria-hidden="true"></i> {{news.add_time | date:"d M Y"}} </span> /
                <span class="name"><i class="fa fa-user" aria-hidden="true"></i> {{news.author}} </span> /
                 <span class="name"> {{first_news.views}}<i class="fa fa-eye" aria-hidden="true"></i> Views</span>
              </p>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </section>
  
  <section id="news-wrapper">
    <div class="container">
      
      {% for category in three_categories %}
      <div class="head-ww" style="position:relative;">
     <h2 style="font-size:20px;">
        <span style="background-color:rgba(37, 67, 105, 1);padding-left:10px;padding-right:30px;padding-top:10px;padding-bottom:10px;color:#ff7777; border-radius: 0vw 10vw 0vw 0vw;position:relative;z-index:9;">{{category.title}}
        </span>
      </h2>
       <marquee style="position:absolute;top:0px;left:0;right:0px;z-index:1;" onmouseover="stop()" onmouseout="start()"> 
  <a href="/detail/{{first_news.id}}"> {{first_news.title}}</a> &nbsp; &nbsp; &nbsp;
   {% for news in three_news %}
    <a href="/detail/{{news.id}}">{{news.title}}</a> &nbsp; &nbsp; &nbsp;
    {% endfor %}
      {% for news in news %}
		{% if forloop.revcounter < 9 %}
      <a href="/detail/{{news.id}}"> {{news.title}} </a> &nbsp; &nbsp; &nbsp;
      {% endif %}
	  	{% endfor %}
</marquee>
 </div>
      <hr style="margin-top:0px;background:rgba(37, 67, 105, 1);">
      <div class="row">
        {% for news in category.news_set.all %}
		{% if forloop.revcounter < 9 %}
        <div class="col-md-3">
          <div class="card mb-4">
            <a href="/detail/{{news.id}}">
              <img src="{{news.image.url}}" class="card-img-top" alt="img">
              <div class="card-body">
                <h5 class="card-title">{{news.title | truncatechars:100 }}</h5>
                <p class="card-text">{{news.detail | truncatechars:100 | safe }}
                </p>
                <span><i class="fa fa-user" aria-hidden="true"></i> {{news.author}}</span> 
                {% comment %} <span><i class="fa fa-folder-open" aria-hidden="true"></i> {{news.type}}</span> <span>/</span> {% endcomment %}
                <span><i class="fa fa-calendar" aria-hidden="true"></i> {{news.add_time | date:"d M Y"}}</span>
                  <span><i class="fa fa-eye" aria-hidden="true"></i> {{news.views}} Views</span>
              </div>
            </a>
          </div>
        </div>
      

        {% endif %}
	  	{% endfor %}
      </div>
       
      {% endfor %}
     
    </div>
  </section>
     
 {% endblock %}

templates/home/khelkud.html
{% extends 'base.html' %}
{% block body %}
			<main class="container mt-3 mb-5" id="news-wrapper">
			<div class="row">
			{% for i in Khelkud %}
			
			<h3 class="border-bottom pb-1 my-4">{{i.title}}</h3>
			{% endfor %}
			<!-- Category Box -->

			{% for Category in K_news %}
             <div class="col-md-3 mb-4">
          <div class="card">
            <a href="/detail/{{Category.id}}">
              <img src="{{Category.image.url}}" class="card-img-top" alt="img">
              <div class="card-body">
                <h5 class="card-title">{{Category.title | truncatechars:100 }}</h5>
                <p class="card-text">{{Category.detail | truncatechars:100 | safe }}
                </p>
                <span>By : {{Category.author}}</span> <span>/</span>
                <span>{{Category.type}}</span> <span>/</span>
                <span>{{Category.add_time | date:"d M Y"}}</span>
              </div>
            </a>
          </div>
        </div>


			{% endfor%}
			<nav aria-label="Page navigation example">
  <ul class="pagination">
	  {% if K_news.has_previous %}
    <li class="page-item"><a class="page-link" href="/khelkud/?page=1">First</a></li>
    <li class="page-item"><a class="page-link" href="/khelkud/?page={{K_news.previous_page_number}}">Previous</a></li>
	{% endif %}
    
	  {% if K_news.has_next %}
    <li class="page-item"><a class="page-link" href="/khelkud/?page={{K_news.next_page_number}}">Next</a></li>
  {% endif %}
</ul>
</nav>
			</div>
			</main>
			
{% endblock%}

templates/home/rajnitic.html
{% extends 'base.html' %}
{% block body %}
			<main class="container mt-3 mb-5" id="news-wrapper">
			<div class="row">
			{% for i in Rajnitic %}
			
			<h3 class="border-bottom pb-1 my-4">{{i.title}}</h3>
			{% endfor %}
			<!-- Category Box -->

			{% for Category in R_news %}
             <div class="col-md-3 mb-4">
          <div class="card">
            <a href="/detail/{{Category.id}}">
              <img src="{{Category.image.url}}" class="card-img-top" alt="img">
              <div class="card-body">
                <h5 class="card-title">{{Category.title | truncatechars:100 }}</h5>
                <p class="card-text">{{Category.detail | truncatechars:100 | safe }}
                </p>
                <span>By : {{Category.author}}</span> <span>/</span>
                <span>{{Category.type}}</span> <span>/</span>
                <span>{{Category.add_time | date:"d M Y"}}</span>
              </div>
            </a>
          </div>
        </div>


			{% endfor%}
			<nav aria-label="Page navigation example">
  <ul class="pagination">
	  {% if R_news.has_previous %}
    <li class="page-item"><a class="page-link" href="/rajnitic/?page=1">First</a></li>
    <li class="page-item"><a class="page-link" href="/rajnitic/?page={{R_news.previous_page_number}}">Previous</a></li>
	{% endif %}
    
	  {% if R_news.has_next %}
    <li class="page-item"><a class="page-link" href="/rajnitic/?page={{R_news.next_page_number}}">Next</a></li>
  {% endif %}
</ul>
</nav>
			</div>
			</main>
			
{% endblock%}